// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYDiFabfGt5NxHJ14l7lRnDMpaSQs-TsY',
    appId: '1:507520596250:web:59f6b394f132a6ca05d4a3',
    messagingSenderId: '507520596250',
    projectId: 'prescription-3c2c9',
    authDomain: 'prescription-3c2c9.firebaseapp.com',
    storageBucket: 'prescription-3c2c9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_y5Bv_L4fPCZJr47XtMlweN2XbHZ_dt4',
    appId: '1:507520596250:android:44f63e6109bc490a05d4a3',
    messagingSenderId: '507520596250',
    projectId: 'prescription-3c2c9',
    storageBucket: 'prescription-3c2c9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaagt5zOitFJsAvijW4R5BYe2J58j8Nis',
    appId: '1:507520596250:ios:5e9eaf55b464a98d05d4a3',
    messagingSenderId: '507520596250',
    projectId: 'prescription-3c2c9',
    storageBucket: 'prescription-3c2c9.appspot.com',
    iosBundleId: 'com.example.abin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaagt5zOitFJsAvijW4R5BYe2J58j8Nis',
    appId: '1:507520596250:ios:5e9eaf55b464a98d05d4a3',
    messagingSenderId: '507520596250',
    projectId: 'prescription-3c2c9',
    storageBucket: 'prescription-3c2c9.appspot.com',
    iosBundleId: 'com.example.abin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYDiFabfGt5NxHJ14l7lRnDMpaSQs-TsY',
    appId: '1:507520596250:web:734a0574e837dbf905d4a3',
    messagingSenderId: '507520596250',
    projectId: 'prescription-3c2c9',
    authDomain: 'prescription-3c2c9.firebaseapp.com',
    storageBucket: 'prescription-3c2c9.appspot.com',
  );
}
